const mongoose = require('mongoose');

const preferencesSchema = new mongoose.Schema({
  general: {
    enablePasscode: { type: Boolean, default: false },
    passcodeHash: { type: String, default: '' },
    businessCurrency: { type: String, default: 'INR' },
    amountDecimalPlaces: { type: String, default: '2' },
    gstin: { type: String, default: '' },
    stopSaleOnNegativeStock: { type: Boolean, default: false },
    blockNewItemsFromTransaction: { type: Boolean, default: false },
    blockNewPartiesFromTransaction: { type: Boolean, default: false },
    estimateQuotation: { type: Boolean, default: true },
    proformaInvoice: { type: Boolean, default: false },
    salePurchaseOrder: { type: Boolean, default: false },
    otherIncome: { type: Boolean, default: true },
    fixedAssets: { type: Boolean, default: false },
    deliveryChallan: { type: Boolean, default: true },
    goodsReturnOnDC: { type: Boolean, default: false },
    printAmountOnDC: { type: Boolean, default: true },
    enableGodown: { type: Boolean, default: true },
    autoBackup: { type: Boolean, default: true },
    backupFrequency: { type: String, default: 'daily' },
    backupRetention: { type: Number, default: 7 },
    auditTrail: { type: Boolean, default: false },
    zoomLevel: { type: String, default: '100' },
    darkMode: { type: Boolean, default: false },
  },
  transaction: {
    invoiceNo: { type: String, default: 'Auto' },
    addTimeOnTransactions: { type: Boolean, default: false },
    cashSaleByDefault: { type: Boolean, default: false },
    billingNameOfParties: { type: String, default: 'Registered' },
    customerPODetails: { type: Boolean, default: false },
    poDate: { type: Boolean, default: false },
    estimateValidityDays: { type: Number, default: 15, min: 0 },
    inclusiveExclusiveTax: { type: String, default: 'Inclusive' },
    displayPurchasePrice: { type: Boolean, default: false },
    lastSalePrice: { type: Boolean, default: true },
    lastPurchasePrice: { type: Boolean, default: true },
    freeItemQuantity: { type: Boolean, default: true },
    count: { type: String, default: '1' },
    transactionWiseTax: { type: Boolean, default: false },
    transactionWiseDiscount: { type: Boolean, default: true },
    roundOffTotal: { type: Boolean, default: true },
    roundingMethod: { type: String, default: 'Normal' },
    eWayBillNo: { type: Boolean, default: false },
    quickEntry: { type: Boolean, default: false },
    doNotShowInvoicePreview: { type: Boolean, default: false },
    passcodeForEditDelete: { type: Boolean, default: false },
    discountDuringPayments: { type: Boolean, default: false },
    linkPaymentsToInvoice: { type: Boolean, default: false },
    dueDatesPaymentTerms: { type: Boolean, default: true },
    showProfitWhileCreatingInvoice: { type: Boolean, default: false },
    termsAndConditions: { type: Boolean, default: true },
    additionalFields: { type: Boolean, default: false },
    transportationDetails: { type: Boolean, default: false },
    additionalCharges: { type: Boolean, default: false },
    salePrefix: { type: String, default: 'SALE-' },
    creditNotePrefix: { type: String, default: 'CN-' },
    saleOrderPrefix: { type: String, default: 'SO-' },
    purchaseOrderPrefix: { type: String, default: 'PO-' },
    estimatePrefix: { type: String, default: 'EST-' },
    proformaPrefix: { type: String, default: 'PRO-' },
    deliveryChallanPrefix: { type: String, default: 'DC-' },
    paymentInPrefix: { type: String, default: 'PI-' },
    receiptPrefix: { type: String, default: 'RCP-' },
  },
  print: {
    balanceAmount: { type: Boolean, default: true },
    currentBalance: { type: Boolean, default: true },
    taxDetails: { type: Boolean, default: true },
    youSaved: { type: Boolean, default: true },
    printAmountWithGrouping: { type: Boolean, default: true },
    amountInWords: { type: Boolean, default: true },
    amountInWordsFormat: { type: String, default: 'Indian' },
    footerSettings: { type: String, default: 'Thank you for your business!' },
    printDescription: { type: Boolean, default: true },
    termsConditions: { type: Boolean, default: true },
    receivedBy: { type: Boolean, default: true },
    deliveredBy: { type: Boolean, default: true },
    signature: { type: Boolean, default: true },
    paymentMode: { type: Boolean, default: true },
    acknowledgement: { type: Boolean, default: false },
    paperSize: { type: String, default: 'A4' },
    orientation: { type: String, default: 'Portrait' },
    companyNameTextSize: { type: String, default: '16' },
    invoiceTextSize: { type: String, default: '14' },
    printOriginalDuplicate: { type: String, default: 'Original' },
    topPDFMargin: { type: String, default: '10' },
    printerType: { type: String, default: 'regular' },
    makeThermalDefault: { type: Boolean, default: false },
    thermalPageSize: { type: String, default: '3inch' },
    thermalCustomChars: { type: String, default: '48' },
    printingType: { type: String, default: 'Text Printing' },
    useTextStyling: { type: Boolean, default: true },
    autoCutPaper: { type: Boolean, default: false },
    openCashDrawer: { type: Boolean, default: false },
    extraLinesAtEnd: { type: String, default: '0' },
    numberOfCopies: { type: String, default: '1' },
    showCompanyName: { type: Boolean, default: true },
    showCompanyLogo: { type: Boolean, default: true },
    showAddress: { type: Boolean, default: true },
    showEmail: { type: Boolean, default: true },
    showPhone: { type: Boolean, default: true },
    showGSTIN: { type: Boolean, default: true },
    thermalTheme1: { type: Boolean, default: true },
    thermalTheme2: { type: Boolean, default: false },
    thermalTheme3: { type: Boolean, default: false },
    thermalTheme4: { type: Boolean, default: false },
    showItemSNo: { type: Boolean, default: true },
    showItemHSN: { type: Boolean, default: true },
    showItemUOM: { type: Boolean, default: true },
    showItemMRP: { type: Boolean, default: true },
    showItemDescription: { type: Boolean, default: true },
    showBatchNo: { type: Boolean, default: true },
    showExpDate: { type: Boolean, default: true },
    showMfgDate: { type: Boolean, default: true },
    showSize: { type: Boolean, default: true },
    showModelNo: { type: Boolean, default: true },
    showSerialNo: { type: Boolean, default: true },
    showTotalItemQty: { type: Boolean, default: true },
    showAmountDecimal: { type: Boolean, default: true },
    receivedAmount: { type: Boolean, default: true },
    tallyTheme: { type: Boolean, default: false },
    landscapeTheme1: { type: Boolean, default: false },
    landscapeTheme2: { type: Boolean, default: false },
    gstTheme: { type: Boolean, default: true },
    accentColor: { type: String, default: '#2563EB' },
    showBankDetails: { type: Boolean, default: true },
    showQRCode: { type: Boolean, default: true },
    showPartyPhone: { type: Boolean, default: true },
    showPartyGSTIN: { type: Boolean, default: true },
    showPartyAddress: { type: Boolean, default: true },
    showTransportDetails: { type: Boolean, default: true },
    additionalField1Label: { type: String, default: 'Additional Field 1' },
    additionalField2Label: { type: String, default: 'Additional Field 2' },
  },
  taxes: {
    enableGST: { type: Boolean, default: true },
    hsnSac: { type: Boolean, default: false },
    additionalCess: { type: Boolean, default: false },
    cessRate: { type: Number, default: 0, min: 0, max: 100 },
    tcsRate: { type: Number, default: 0, min: 0, max: 100 },
    tdsRate: { type: Number, default: 0, min: 0, max: 100 },
    reverseCharge: { type: Boolean, default: false },
    placeOfSupply: { type: Boolean, default: true },
    compositionScheme: { type: Boolean, default: false },
    enableTCS: { type: Boolean, default: false },
    enableTDS: { type: Boolean, default: false },
    taxRates: { type: [mongoose.Schema.Types.Mixed], default: [
      { igst: 0, cgst: 0, sgst: 0, label: 'GST 0%' },
      { igst: 0.25, cgst: 0.125, sgst: 0.125, label: 'GST 0.25%' },
      { igst: 3, cgst: 1.5, sgst: 1.5, label: 'GST 3%' },
      { igst: 5, cgst: 2.5, sgst: 2.5, label: 'GST 5%' },
      { igst: 12, cgst: 6, sgst: 6, label: 'GST 12%' },
      { igst: 18, cgst: 9, sgst: 9, label: 'GST 18%' },
      { igst: 28, cgst: 14, sgst: 14, label: 'GST 28%' },
      { igst: 40, cgst: 20, sgst: 20, label: 'GST 40%' },
    ]},
  },
  transactionMessage: {
    sendViaVyapar: { type: Boolean, default: false },
    sendViaWhatsApp: { type: Boolean, default: false },
    sendMessageToParty: { type: Boolean, default: true },
    sendCopyToSelf: { type: Boolean, default: false },
    sendTransactionUpdates: { type: Boolean, default: true },
    autoShareInvoices: { type: Boolean, default: false },
    currentBalance: { type: Boolean, default: true },
    webInvoiceLink: { type: Boolean, default: true },
    paymentLink: { type: Boolean, default: true },
    autoMsgSales: { type: Boolean, default: true },
    autoMsgPurchase: { type: Boolean, default: true },
    autoMsgSalesReturn: { type: Boolean, default: false },
    autoMsgPurchaseReturn: { type: Boolean, default: false },
    autoMsgPaymentIn: { type: Boolean, default: true },
    autoMsgPaymentOut: { type: Boolean, default: true },
    autoMsgSaleOrder: { type: Boolean, default: false },
    autoMsgPurchaseOrder: { type: Boolean, default: false },
    autoMsgEstimate: { type: Boolean, default: false },
    autoMsgProforma: { type: Boolean, default: false },
    autoMsgDeliveryChallan: { type: Boolean, default: false },
    autoMsgCancelledInvoice: { type: Boolean, default: false },
    messageTemplate: { type: String, default: '' },
    templates: { type: mongoose.Schema.Types.Mixed, default: {} },
  },
  party: {
    partyGrouping: { type: Boolean, default: true },
    shippingAddress: { type: Boolean, default: true },
    printShippingAddress: { type: Boolean, default: false },
    managePartyStatus: { type: Boolean, default: true },
    paymentReminder: { type: Boolean, default: true },
    reminderDays: { type: String, default: '7' },
    enableLoyalty: { type: Boolean, default: false },
    customFieldDefs: { type: [mongoose.Schema.Types.Mixed], default: [] },
    partyShowAddresses: { type: Boolean, default: true },
    partyShowStatutory: { type: Boolean, default: true },
    partyShowPricing: { type: Boolean, default: true },
    partyShowBankDetails: { type: Boolean, default: false },
    partyShowNotes: { type: Boolean, default: true },
    partyDefaultAddress: { type: String, default: '' },
    partyDefaultPaymentTerms: { type: String, default: '' },
    partyDefaultBanks: { type: String, default: '' },
  },
  item: {
    enableItem: { type: Boolean, default: true },
    productService: { type: String, default: 'Both' },
    barcodeScan: { type: Boolean, default: true },
    stockMaintenance: { type: Boolean, default: true },
    manufacturing: { type: Boolean, default: false },
    lowStockDialog: { type: Boolean, default: true },
    itemUnits: { type: String, default: 'Piece' },
    unit: { type: String, default: 'Pcs' },
    itemCategory: { type: Boolean, default: false },
    partyWiseRate: { type: Boolean, default: false },
    description: { type: Boolean, default: true },
    itemWiseTax: { type: Boolean, default: true },
    itemWiseDiscount: { type: Boolean, default: true },
    wholesalePrice: { type: Boolean, default: true },
    updateSalePriceAuto: { type: Boolean, default: false },
    mrp: { type: Boolean, default: true },
    calculateTaxOnMRP: { type: Boolean, default: false },
    serialNumberTracking: { type: Boolean, default: false },
    batchTracking: { type: Boolean, default: false },
    expiryDate: { type: Boolean, default: false },
    manufacturingDate: { type: Boolean, default: false },
    modelNumber: { type: Boolean, default: false },
    size: { type: Boolean, default: false },
    customFieldDefs: { type: [mongoose.Schema.Types.Mixed], default: [] },
  },
  accounting: {
    enableAccounting: { type: Boolean, default: true },
    allowJournalEntries: { type: Boolean, default: true },
  },
  serviceReminders: {
    enableReminders: { type: Boolean, default: true },
    reminderInterval: { type: String, default: '30' },
    autoFollowUp: { type: Boolean, default: true },
  },
  notifications: {
    enableNotifications: { type: Boolean, default: true },
    new_sale: { type: Boolean, default: true },
    new_purchase: { type: Boolean, default: true },
    payment_received: { type: Boolean, default: true },
    payment_due: { type: Boolean, default: true },
    low_stock: { type: Boolean, default: true },
    sale_return: { type: Boolean, default: true },
    purchase_return: { type: Boolean, default: true },
    expense_created: { type: Boolean, default: true },
    party_added: { type: Boolean, default: true },
    bank_transaction: { type: Boolean, default: true },
    service_reminder: { type: Boolean, default: true },
    sale_cancelled: { type: Boolean, default: true },
    purchase_cancelled: { type: Boolean, default: true },
    purchase_updated: { type: Boolean, default: true },
    purchase_deleted: { type: Boolean, default: true },
    expense_updated: { type: Boolean, default: true },
    expense_deleted: { type: Boolean, default: true },
    payment_out: { type: Boolean, default: true },
    payment_out_deleted: { type: Boolean, default: true },
    email: {
      enabled: { type: Boolean, default: false },
      smtpHost: { type: String, default: '' },
      smtpPort: { type: String, default: '587' },
      smtpSecure: { type: Boolean, default: false },
      smtpUser: { type: String, default: '' },
      smtpPass: { type: String, default: '' },
      fromEmail: { type: String, default: '' },
      paymentReceived: { type: Boolean, default: true },
      lowStock: { type: Boolean, default: true },
    },
    sms: {
      enabled: { type: Boolean, default: false },
      provider: { type: String, default: 'generic' },
      apiKey: { type: String, default: '' },
      senderId: { type: String, default: '' },
      accountSid: { type: String, default: '' },
      authToken: { type: String, default: '' },
      fromNumber: { type: String, default: '' },
      paymentReceived: { type: Boolean, default: true },
      lowStock: { type: Boolean, default: true },
    },
    push: {
      enabled: { type: Boolean, default: false },
      paymentReceived: { type: Boolean, default: true },
      lowStock: { type: Boolean, default: true },
      newSale: { type: Boolean, default: false },
      newPurchase: { type: Boolean, default: false },
    },
  },
}, { _id: false });

const settingSchema = new mongoose.Schema({
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, unique: true, index: true },
  ownerName: { type: String, default: '', trim: true },
  businessName: { type: String, default: '', trim: true },
  phone: { type: String, default: '', trim: true },
  email: { type: String, default: '', lowercase: true, trim: true },
  address: { type: String, default: '', trim: true },
  gstNumber: { type: String, default: '', trim: true },
  invoicePrefix: { type: String, default: 'INV-', trim: true },
  invoiceNote: { type: String, default: '', trim: true },
  logo: { type: String },
  currency: { type: String, default: '₹', trim: true },
  state: { type: String, default: '', trim: true },
  isInterState: { type: Boolean, default: false },
  bankName: { type: String, default: '', trim: true },
  bankAccountNumber: { type: String, default: '', trim: true },
  bankIfsc: { type: String, default: '', trim: true },
  bankBranch: { type: String, default: '', trim: true },
  upiId: { type: String, default: '', trim: true },
  businessType: { type: String, enum: ['retail', 'wholesale', 'manufacturing', 'service', 'other'], default: 'retail' },
  businessCategory: { type: String, default: '', trim: true },
  pincode: { type: String, default: '', trim: true },
  signature: { type: String, default: '' },
  accountBooksBeginningDate: { type: Date, default: Date.now },
  financialYearLock: {
    isLocked: { type: Boolean, default: false },
    lockedUntil: { type: Date, default: null },
    closedFY: { type: String, default: '' },
    closedAt: { type: Date, default: null },
  },
  sharedWith: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
  preferences: { type: preferencesSchema, default: () => ({}) },
}, { timestamps: true });

module.exports = mongoose.model('Setting', settingSchema);
